#app_key: <%= ENV["DROPBOX_APP_KEY"] %>
#app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
#access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
#access_token_secret: <%= ENV["DROPBOX_ACCESS_TOKEN_SECRET"] %>
#user_id: <%= ENV["DROPBOX_USER_ID"] %>
#access_type: <%= ENV["DROPBOX_ACCESS_TYPE"] %>

#app_key: <%= ENV["rirzg3k330zg8a3"] %>
#app_secret: <%= ENV["lb93gsg1e0hj5r5"] %>
#access_token: <%= ENV["cn611bh6vly3mrk"] %>
#access_token_secret: <%= ENV["o9kwxcil3ifaac5"] %>
#user_id: <%= ENV["148455259"] %>
#access_type: <%= ENV["app_folder"] %>

app_key: rirzg3k330zg8a3
app_secret: lb93gsg1e0hj5r5
access_token: cn611bh6vly3mrk
access_token_secret: o9kwxcil3ifaac5
user_id: 148455259
access_type: app_folder