# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create({"email"=>"dr@mymail.com", "first_name"=>"Dominic", "last_name"=>"Ramms", "password"=>"123456"})
User.create({"email"=>"sn@mymail.com", "first_name"=>"Sascha", "last_name"=>"Nonte", "password"=>"123456"})
User.create({"email"=>"mc@mymail.com", "first_name"=>"Marvin", "last_name"=>"Caspar", "password"=>"123456"})
User.create({"email"=>"tp@mymail.com", "first_name"=>"Tobias", "last_name"=>"Prein", "password"=>"123456"})
User.create({"email"=>"tk@mymail.com", "first_name"=>"Till", "last_name"=>"Krueger", "password"=>"123456"})
User.create({"email"=>"sm@mymail.com", "first_name"=>"Simon", "last_name"=>"Miketta", "password"=>"123456"})
User.create({"email"=>"md@mymail.com", "first_name"=>"Malte", "last_name"=>"Dauskart", "password"=>"123456"})
User.create({"email"=>"js@mymail.com", "first_name"=>"Jannik", "last_name"=>"Scheik", "password"=>"123456"})
User.create({"email"=>"ak@mymail.com", "first_name"=>"Andre", "last_name"=>"Konetzka", "password"=>"123456"})
User.create({"email"=>"ja@mymail.com", "first_name"=>"Jonas", "last_name"=>"Assies", "password"=>"123456"})
User.create({"email"=>"ga@mymail.com", "first_name"=>"Gamze", "last_name"=>"Atar", "password"=>"123456"})
User.create({"email"=>"jb@mymail.com", "first_name"=>"Julian", "last_name"=>"Beisenkoetter", "password"=>"123456"})
User.create({"email"=>"sb@mymail.com", "first_name"=>"Simon", "last_name"=>"Bern", "password"=>"123456"})
User.create({"email"=>"bb@mymail.com", "first_name"=>"Bastian", "last_name"=>"Bleker", "password"=>"123456"})
User.create({"email"=>"cb@mymail.com", "first_name"=>"Christian", "last_name"=>"Bootsmann", "password"=>"123456"})
User.create({"email"=>"sb@mymail.com", "first_name"=>"Sven", "last_name"=>"Buecker", "password"=>"123456"})
User.create({"email"=>"rc@mymail.com", "first_name"=>"Raphael", "last_name"=>"Chmiel", "password"=>"123456"})
User.create({"email"=>"fc@mymail.com", "first_name"=>"Felix", "last_name"=>"Claus", "password"=>"123456"})
User.create({"email"=>"sd@mymail.com", "first_name"=>"Stephan", "last_name"=>"Depenwisch", "password"=>"123456"})
User.create({"email"=>"sd@mymail.com", "first_name"=>"Stephan", "last_name"=>"Depenwisch", "password"=>"123456"})
User.create({"email"=>"cd@mymail.com", "first_name"=>"Christopher", "last_name"=>"Dicke", "password"=>"123456"})
User.create({"email"=>"be@mymail.com", "first_name"=>"Benedikt", "last_name"=>"Erdmann", "password"=>"123456"})
User.create({"email"=>"ji@mymail.com", "first_name"=>"Joyce", "last_name"=>"Iben", "password"=>"123456"})


Friend.create(:user_id => 1, :friend_id => 2)
Friend.create(:user_id => 2, :friend_id => 1)
Friend.create(:user_id => 1, :friend_id => 3)
Friend.create(:user_id => 3, :friend_id => 1)
Friend.create(:user_id => 1, :friend_id => 4)
Friend.create(:user_id => 4, :friend_id => 1)
Friend.create(:user_id => 1, :friend_id => 5)
Friend.create(:user_id => 5, :friend_id => 1)
Friend.create(:user_id => 1, :friend_id => 6)
Friend.create(:user_id => 6, :friend_id => 1)
Friend.create(:user_id => 1, :friend_id => 7)
Friend.create(:user_id => 7, :friend_id => 1)
Friend.create(:user_id => 1, :friend_id => 8)
Friend.create(:user_id => 8, :friend_id => 1)

Friend.create(:user_id => 2, :friend_id => 3)
Friend.create(:user_id => 3, :friend_id => 2)
Friend.create(:user_id => 2, :friend_id => 4)
Friend.create(:user_id => 4, :friend_id => 2)
Friend.create(:user_id => 2, :friend_id => 5)
Friend.create(:user_id => 5, :friend_id => 2)
Friend.create(:user_id => 2, :friend_id => 6)
Friend.create(:user_id => 6, :friend_id => 2)
Friend.create(:user_id => 2, :friend_id => 7)
Friend.create(:user_id => 7, :friend_id => 2)
Friend.create(:user_id => 2, :friend_id => 8)
Friend.create(:user_id => 8, :friend_id => 2)

Friend.create(:user_id => 3, :friend_id => 4)
Friend.create(:user_id => 4, :friend_id => 3)
Friend.create(:user_id => 3, :friend_id => 5)
Friend.create(:user_id => 5, :friend_id => 3)
Friend.create(:user_id => 3, :friend_id => 6)
Friend.create(:user_id => 6, :friend_id => 3)
Friend.create(:user_id => 3, :friend_id => 7)
Friend.create(:user_id => 7, :friend_id => 3)
Friend.create(:user_id => 3, :friend_id => 8)
Friend.create(:user_id => 8, :friend_id => 3)

Friend.create(:user_id => 15, :friend_id => 16)
Friend.create(:user_id => 16, :friend_id => 15)
Friend.create(:user_id => 15, :friend_id => 17)
Friend.create(:user_id => 17, :friend_id => 15)
Friend.create(:user_id => 15, :friend_id => 18)
Friend.create(:user_id => 18, :friend_id => 15)


FriendRequests.create(:user_id => 1, :friend_id => 15)
FriendRequests.create(:user_id => 2, :friend_id => 15)
FriendRequests.create(:user_id => 3, :friend_id => 15)